- name: Upgrade pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"

# Install from PyPi
- block:
    - name: Install Girder Worker
      pip:
        name: girder-worker
        state: "{{ 'latest' if girder_worker_update else 'present' }}"
        version: "{{ girder_worker_pypi_version | default(omit) }}"
        virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"

    - name: Install Girder Worker Plugins
      pip:
        name: "girder-worker[{{ item }}]"
        state: "{{ 'latest' if girder_worker_update else 'present' }}"
        version: "{{ girder_worker_pypi_version | default(omit) }}"
        virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"
      with_items: "{{ girder_worker_plugins }}"
  when: girder_worker_install_source == "pypi"

# Install from Git
- block:
    - name: Install Girder Worker
      pip:
        name: "{{ girder_worker_path }}"
        extra_args: "--editable"
        virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"

    - name: Install Girder Worker Plugins
      pip:
        name: "{{ girder_worker_path }}[{{ item }}]"
        extra_args: "--editable"
        virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"
      with_items: "{{ girder_worker_plugins }}"
  when: girder_worker_install_source == "git"
